@startuml "ER 2 student"

skinparam linetype ortho
hide circle

entity student {
    * id: integer <<generated>>
    --
    * training_id: integer
    * user_id: integer
    --
    ...
}

note right of student: Договор со студентом о \nпоступлении на курс

@enduml
