@startuml "ER 2 task"

skinparam linetype ortho
hide circle

entity task {
    * id: integer
    --
    training_id: integer
    --
    condition: text
    ...
}

note right of task: Условие\n задачи

@enduml
