@startuml "ER Manager"

skinparam linetype ortho
hide circle


entity user{
    * id: integer <<generated>>
    --
    role_id: integer
    ...
}

entity decition {
    *id: integer <<generated>> 
    --
    *task_id: integer
    *student_id
    *language_id
    --
    code: text
    success: boolean
    attempt: integer
    done_at: timestamp
    ...
}

entity training {
    * id: integer <<generated>>
    --
    name: string
    ...
}

entity student {
    * id: integer <<generated>>
    --
    * training_id: integer
    * user_id: integer
    --
    ...
}

entity professor {
    * id: integer <<generated>>
    --
    training_id: integer
    user_id: integer
    --
    ...
}

entity language {
    * id: integer <<generated>>
    --
    name: string
    ...
}

entity task {
    * id: integer
    --
    training_id: integer
    --
    condition: text
    ...
}

decition }-- student 
student }-u- training
student }-- user
professor }-u- training
professor }-- user
language -u-{ decition
task }-l- training


note right of student: Договор со студентом о \nпоступлении на курс
note right of professor: Договор с \nпреподавателем\n о проведении курса
note right of user: Пользователи\n системы
note right of decition: Отправленное\n решение\n задачи
note right of training: Преподаваемый\n курс

note right of language: Язык \nпрограммрования


@enduml