@startuml "ER student"

skinparam linetype ortho
hide circle


entity task {
    * id: integer
    --
    training_id: integer
    --
    condition: text
    ...
}

entity decision {
    *id: integer <<generated>> 
    --
    *task_id: integer
    *student_id
    *language_id
    --
    code: text
    success: boolean
    attempt: integer
    done_at: timestamp
    ...
}


entity decision_test {
    * id:integer <<generated>>
    --
    * test_id: integer
    * decision_id: integer
    --
    reason_id: integer
    result: enum('failed', 'passed')
    ...
}

entity reason {
    * id: integer <<generated>>
    --
    name: string
    ...
}


entity training {
    * id: integer <<generated>>
    --
    name: string
    ...
}

entity student {
    * id: integer <<generated>>
    --
    * training_id: integer
    * user_id: integer
    --
    ...
}

entity language {
    * id: integer <<generated>>
    --
    name: string
    ...
}

task --{ decision
decision }-- student 
decision_test }-l- decision
reason -u-{ decision_test
task }-l- training
student }-u- training
language -u-{ decision


note right of student: Договор со студентом о \nпоступлении на курс
note right of decision: Отправленное\n решение\n задачи
note right of training: Преподаваемый\n курс
note right of task: Условие\n задачи

note right of decision_test: Результаты проверки\n задачи
note right of reason: Причина отказа\n в приёме \nрешения
note right of language: Язык \nпрограммрования


@enduml